### ISSUE TITLE
Stack Creation Failed

### ISSUE THREAD

**Issue by ViVa98** [aws-samples/aws-saas-factory-bootcamp#63]
InvokeLambdaCopyS3Objects

CREATE_FAILED

Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/07/14/[$LATEST]xxxxxxxxxxxxxxxxxxxx (RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

There is no log stream created in cloudwatch when opened to see logs for this error

**Comment by brtrvn** [comment]
I can't replicate this issue. To debug, you can edit the workshop.yml file and add `DeletionPolicy: Retain` to the `CopyS3ObjectsLogs` resource. It would look like this:

```yaml
CopyS3ObjectsLogs:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/saas-bootcamp-s3-copy-${AWS::Region}
      RetentionInDays: 7
```

Let us know what you find in the logs. You'll need to manually delete this log group before creating another copy of this CloudFormation stack in the same region.
